### ISSUE TITLE
Finalize a Data Model

### ISSUE THREAD

**Issue by oscarsyu** [sfbrigade/datasci-earthquake#11]
## Context
We need a data model finalized so that backend can implement it and serve our data to users.  This task is to work with Backend and Data Science to determine which data we'll need and how it'll be organized.

[Link in proposed data model from @katiefg]

**Comment by mackcooper1408** [comment]
@katiefg don't hesitate to put up any questions, also might be something we can work on/finalize as a mini-group

**Comment by katiefg** [comment]
Data tables with variable column names, constraints, and descriptions documented in markdown on wiki's ["Database Tables" page](https://github.com/sfbrigade/datasci-earthquake/wiki/Database-Tables) under the "Database (SQLAlchemy)" section.  

Open to any questions, concerns, or edits!

**Comment by katiefg** [comment]
Data tables with variable column names, constraints, and descriptions documented in markdown on wiki's ["Database Tables" page](https://github.com/sfbrigade/datasci-earthquake/wiki/Database-Tables) under the "Database (SQLAlchemy)" section.

Open to any questions, concerns, or edits!
