### ISSUE TITLE
Liquefaction Dataset EDA

### ISSUE THREAD

**Issue by oscarsyu** [sfbrigade/datasci-earthquake#13]
## Context
This is a task to perform basic EDA on the Liquefaction dataset.  We need to make a determination of whether or not we need to use this dataset.

The liquefaction dataset is described as:

Map delineation of the different types and ages of Quaternary deposits supports evaluation of susceptibility to liquefaction. These areas can be expected to experience increased damage from ground shaking during an earthquake. The dataset displays where high and very high liquefaction hazard areas are found. This was used for the 2019 HCR update process.

The output from this analysis is a general "state of the union" report:

Please analyze this dataset along these dimensions:
- Is the data usable?
- Is the data's coverage good?
- General EDA on liquefaction zones - what are our data distributions, do we see any correlations/patterns within this dataset
- Anything interesting you find

## Definition of Done
- a finished report/notebook on your assessment of the quality of the data
- Review the results at a meeting with the eng team for discussion.

## Engineering Details
- Please also work with the person who is building the centralized documentation on metric definitions and citations

**Comment by gh-ppolk** [comment]
Datasets are listed [here](https://docs.google.com/spreadsheets/d/1cDEH2MJaumxk2I17eBdEa3XBe-1XNGuM8KkrTsPYrbw/edit?gid=0#gid=0)

**Comment by oscarsyu** [comment]
@leela-solomon putting your notebook here: https://colab.research.google.com/drive/1JrXsDYjmp0iLEHOfSapWvT1TNEYLyyHI?usp=sharing#scrollTo=dhMEOZamRrMs
