### ISSUE TITLE
Configure App Environments

### ISSUE THREAD

**Issue by mackcooper1408** [sfbrigade/datasci-earthquake#27]
There's not much to add here until these issues (#22 and #23 are done)

## Context
In order to deploy our application and work with containerization tools like Docker, we'll need some extra configuration to use certain Environment variables. The easiest option for making this work is via a secret `.env` file that will not be checked into git version history.

## Definition of Done
1. environment configuration is complete for front and back end with the app now pulling key variables like "Environment", "Database URL", etc. from an "ENV" file (`.env`)
2. env configuration has appropriate defaults for working with the app in development
3. `.gitignore` is updated to not check the env file into git history
4. README is updated with details on how this config is setup and what variables may be useful (if any at this point) to add to your local `.env`

## Engineering Details
- see [this doc](https://fastapi.tiangolo.com/advanced/settings/) for details on completing the setup in FastAPI.
  - Also, take a look at how the configuration is done in this [template app](https://github.com/fastapi/full-stack-fastapi-template)
- it [appears](https://nextjs.org/docs/pages/building-your-application/configuring/environment-variables) NEXT has native support for .env files... so yay!

**Comment by agennadi** [comment]
Done

**Comment by agennadi** [comment]
Done
