### ISSUE TITLE
Dockerize the application

### ISSUE THREAD

**Issue by mackcooper1408** [sfbrigade/datasci-earthquake#28]
_**This can probably be done at any time, but note that there's not much to do here until general env and db configuration is complete. see #22 #23 #27**_

## Context
Let's make development easier by configuring Docker to build and run the application on any device.

## Definition of Done
1. Docker config is complete and the app is able to be run via Docker compose
2. README is updated with instructions on how to install docker and use it to run the app

## Engineering Details
1. Docker, Next and FastAPI have great docs for this. There's also [this demo project](https://github.com/fastapi/full-stack-fastapi-template) that uses Docker that can serve as a great configuration example

**Comment by agennadi** [comment]
Done
