### ISSUE TITLE
Create metric definition centralized documentation

### ISSUE THREAD

**Issue by oscarsyu** [sfbrigade/datasci-earthquake#31]
## Context
As part of this project, we have multiple data sources and potentially calculated metrics.  We want to be able to store this in a consistent manner and in a centralized location
## Definition of Done

Some sort of doc/system that is communicated out to the team for storing metric definitions and data citations:

- Citations: clearly cite datasources so that the team can track how it was created, who manages it and how frequently will it be updated.
- Equations: if we create any calculated fields, document somewhere the equation that was used.
- figure out if we want to store them in Github, a doc, or some other piece of software

**Comment by mackcooper1408** [comment]
this looks similar to some of the other documentation issues, maybe we can combine with those? Also, let's come to a conclusion quickly on where to document things and note that in the DoD
