### ISSUE TITLE
Set Up Routing for Core Pages

### ISSUE THREAD

**Issue by mantuok** [sfbrigade/datasci-earthquake#35]
## Context
The app will have multiple pages, we need to set up the routing, including dynamic routing for specific entities. The preliminary pages are: Homepage, Selected address, Resources, About, and Methodology.

## Definition of Done
1. The pages are functional
2. Dynamic routing is configured
3. Navigation works correctly
4. Fallback pages for invalid routes are implemented

## Engineering Details
Use the Next.js 13 App Router system and organize pages within the app directory.

_Testing Criteria_
- Each page displays a placeholder with the page name.
- Navigation between pages works without errors.
- Dynamic routes display the correct content for entities.
- Invalid routes show the fallback page (e.g., 404 error).

**Comment by mackcooper1408** [comment]
I think we can actually begin working on this asap. The current Figma should have the first couple of pages laid out, so I think if you update this issue to specify exactly which pages we need and link to the figma, then you can mark this as ready to implement. I also think it's appropriate to add some testing criteria (i.e. for each page x, y, and z, a user should be able to see a "dummy" placeholder page that says the name of the page).
