### ISSUE TITLE
Integrate ChakraUI for UI Components

### ISSUE THREAD

**Issue by mantuok** [sfbrigade/datasci-earthquake#36]
## Context
As ChakraUI will be the primary design system for the web app, we need to integrate it into the Next.js 13 project to begin building reusable UI components.

## Definition of Done
1. ChakraUI is installed
2. The app is wrapped with ChakraProvider in the layout file.
3. An empty custom theme is defined (for future update, once the design is ready), and the layout file is updated to use this theme.

**Comment by mackcooper1408** [comment]
let's add a little bit more detailed on what "properly configured" actually means, then I think this can be marked as ready to implement. It's also definitely okay at this point to say that we'll just have standard config until we build out the design system
