### ISSUE TITLE
Build Reusable UI Components Library

### ISSUE THREAD

**Issue by mantuok** [sfbrigade/datasci-earthquake#38]
This is blocked till we get some input from design teams

## Context
Build a library of reusable components that will help maintain consistency across the app. These components should follow design guidelines and be built using ChakraUI. 

## Definition of Done
A set of base reusable components is implemented (e.g., buttons, inputs, modals, cards, etc.).

## Engineering Details
Create components in a components folder of the project. Extend ChakraUI components using its extendTheme function to adjust base styles as needed.

**Comment by mackcooper1408** [comment]
I like this as a general umbrella task, but once we're ready, let's split this up into separate issues for each component that includes the specific Figma design and perhaps some testing criteria

**Comment by mackcooper1408** [comment]
Handled via PR
