### ISSUE TITLE
Build a Component Test Page for Showcasing UI Components

### ISSUE THREAD

**Issue by mantuok** [sfbrigade/datasci-earthquake#39]
_Can be implemented once issue #38 is done_

## Context
Build a component test page that provides an accessible location for reviewing all the components built so far. This will help with visual inspection of the components, ensuring they behave correctly in various states. In addition, it will serve as a reference for new developers to understand the available UI components and their variants quickly.
The page will display a list of components, each labeled with a corresponding header, and render the component in several variants. 

## Definition of Done
1. A dedicated route (e.g., /components-test) has been created in the app.
2. The page includes headers labeling each component, with the component displayed below each header.
3. Each component is rendered in multiple variants (different sizes, colors, states, etc., as applicable).

**Comment by mackcooper1408** [comment]
I think we can actually unblock this and build the initial page into the router. Then, as part of the DoD ("Definition of Done") for each component we build we can say "add this component to the test page for people to see/review"
