### ISSUE TITLE
Setup initial Wiki

### ISSUE THREAD

**Issue by mackcooper1408** [sfbrigade/datasci-earthquake#42]
## Context
We need a place to keep docs!

## Definition of Done
- Engineering wiki landing page has basic details and info about our project and tools

## Engineering Details
- This is not the Readme, so doesn't need build or setup information, should be focused on data, architecture, system overviews, tooling, etc.

**Comment by katiefg** [comment]
Wiki is setup and populated with some very basic information and structure at [https://github.com/sfbrigade/datasci-earthquake/wiki](https://github.com/sfbrigade/datasci-earthquake/wiki)

Please feel free to add and edit as needed.
