### ISSUE TITLE
Add Python Linter (Black)

### ISSUE THREAD

**Issue by mackcooper1408** [sfbrigade/datasci-earthquake#43]
## Context
The app currently has a linter setup for Javascript (ESLint), but nothing for Python.

## Definition of Done
- [Black](https://pypi.org/project/black/) linting library is installed and configured
- a script is added in `package.json` to run the linter

## Engineering Details
I'd recommend whatever standard configuration Black comes with for now, but it's certainly dealer's choice to configure this however you see fit

**Comment by agennadi** [comment]
Hi @mackcooper1408! Should I add Black to the `package.json` or create a pre-commit hook instead? Wouldn’t adding the Python linter to the npm script tightly couple the frontend and backend?
