### ISSUE TITLE
Add in Datasets

### ISSUE THREAD

**Issue by oscarsyu** [sfbrigade/datasci-earthquake#44]
## Context
We have a few older files, PRs to merge in, and a lack of organization for the analytics sub-directory.  This is a task to clean that up.

## Definition of Done
- Clean out unnecessary configs, python files. Keep basically what is necessary to run the streamlit app
- create a folder structure that makes it easy for new reports an analysis to be added in
- a quick How-to guide on how to add analysis in
- add in a .gitignore so that extraneous files aren't added in for streamlit and jupyter notebook PR pushes.
- Copies of our datasets ready for analytics 
  - specifically soft story, neighborhood, seismic, liquefaction 
## Technical Details
- None - should be pretty straightforward

**Comment by mackcooper1408** [comment]
this is COMPLETE
