### ISSUE TITLE
Implement Postgres Database

### ISSUE THREAD

**Issue by trew-boisvert** [sfbrigade/datasci-earthquake#54]
## Context
The SQLAlchemy models need to be used to implement a Postgres database, and then some dummy data needs to be created to test the models.  The database will be integrated into our backend, and future services will interact with it via SQLAlchemy.  
- Set up PostgreSQL locally for development and testing.
- Create a PostgreSQL instance for production.
- Integrate Postgres with the existing codebase, and use existing models to create initial tables
- Implement basic CRUD operations for the main tables using SQLAlchemy models.
- Add initial data seeding

## Definition of Done

- A PostgreSQL database instance is running and connected to the application.
- Database schema is defined and aligned with the project's data needs.
- Database is fully integrated with the backend (via SQLAlchemy).
- Migrations can be easily applied through Alembic or the chosen migration tool.
- All tests related to the database operations pass successfully.
 

## Engineering Details
Database Version: PostgreSQL 13+ recommended.
ORM: We will use SQLAlchemy as the ORM layer to interact with the database.
Migrations: Alembic will be used for handling schema migrations.
TODO lives on backend branch in api/index.py: https://github.com/sfbrigade/datasci-earthquake/blob/backend/api/index.py

**Comment by mackcooper1408** [comment]
Handled for local, will make a more specific issue for hosting in production
