### ISSUE TITLE
Add Information Card Component

### ISSUE THREAD

**Issue by mantuok** [sfbrigade/datasci-earthquake#89]
## Context
Develop a responsive Information Card component based on the provided design specifications. The card will display key details about services, grants, and web resources, and it will be reusable. These cards will be integrated into the app within a responsive layout and populated with available data.

[Figma Design](https://www.figma.com/design/AGadwQcQH5kNn2D93TVOAC/Design?node-id=189-319&node-type=canvas&t=WiiAWylPo18xUxgB-0)

## Definition of Done
- A fully functional responsive Information Card component.
- The component should be reusable.
- Static data should be stored in a separate file.
- Alignment with the provided design specifications (layout, spacing, typography, colors).
- The card layout adapts to various screen sizes.
- Unit tests created and passed using Jest to verify the component’s functionality.
- The Information Card component should be added to the component test library.

## Engineering Details
- Built with React and styled using Chakra UI
- The component's content will be sourced from a data.ts file, which should be created to store all static data.
- Static data is passed as props

**Comment by nickvisut** [comment]
Nice write-up. Is the static data meant to be passed in via props?

**Comment by mantuok** [comment]
Yes, I've added it in the Engineering Details, thank you :)
